name: Room-42

on:
  push:
    branches:
      - main
    paths:
      - "content/escapeRoom/room_42/**"
  pull_request:
    branches:
      - main
    paths:
      - "content/escapeRoom/room_42/**"

jobs:
  test:
    name: "Test Room 42"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq jq rsync xxd openssl netcat-openbsd wget curl bc

      - name: Run Room 42 Solution
        working-directory: content/escapeRoom/room_42
        run: bash _solution.sh
        timeout-minutes: 2
