name: Room-03

on:
  push:
    branches:
      - main
    paths:
      - "content/escapeRoom/room_03/**"
      - ".github/workflows/room-03.yml"
  pull_request:
    branches:
      - main
    paths:
      - "content/escapeRoom/room_03/**"
      - ".github/workflows/room-03.yml"
  workflow_dispatch:

jobs:
  test:
    name: "Test Room 03"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq jq rsync xxd openssl netcat-openbsd wget curl bc

      - name: Run Room 03 Solution
        working-directory: content/escapeRoom/room_03
        run: bash _solution.sh
        timeout-minutes: 2
