name: Deploy To Vercel

on:
  push:
    paths:
      - Labs/**
      - mkdocs.yml

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy To Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: pip install -r mkdocs/requirements.txt

      - name: Build Documentation
        run: mkdocs build

      - name: Deploy to Vercel
        working-directory: mkdocs-site
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
